### ISSUE TITLE
DFU USB Class

### ISSUE THREAD

**Issue by beriberikix** [thegecko/webusb#24]
http://wiki.openmoko.org/wiki/USB_DFU

Have you considered adding DFU support? The idea is to build node.js tools that can program a device without the need for `dfu-util`. There's a WebUSB-specific project that could be inspiration: https://devanlai.github.io/webdfu/dfu-util/

**Comment by thegecko** [comment]
@beriberikix That is an interesting idea.

The scope of this project is to implement the [WebUSB specification](https://wicg.github.io/webusb/) within `Node.js`, so I think adding specific DFU functionality such as this is beyond the scope.

There shouldn't be any reason why this library can't be used with `dfu-util` instead of in the browser, it should be trivial to try out. Let me know how you get on.

There are a few other projects which exist to update devices using JavaScript, which I have had working both in-browser and Node.js, however:

- https://github.com/ARMmbed/dapjs which aims to expose the CMSIS-DAP Arm Mbed debug interface in JavaScript
- https://github.com/thegecko/web-bluetooth-dfu uses [web-bluetooth](https://webbluetoothcg.github.io/web-bluetooth/) (and can be done in `Node.js` using the [webbluetooth](https://www.npmjs.com/package/webbluetooth) npm package)
